[package]
name = "sagent-common"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-appender.workspace = true
regex.workspace = true
anyhow.workspace = true

[dev-dependencies]
tempfile = "3"
