[package]
name = "sagent-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "sagent"
path = "src/main.rs"

[dependencies]
clap.workspace = true
anyhow.workspace = true
sagent-common.workspace = true
sagent-proto.workspace = true
sagent-config.workspace = true
